module.exports = {
  NAMESPACE_ID: "AveJ7unGGB",
  ACCESS_SECRET: "0gXO5KjX3Q0Jqc2AO3pGcULXU5_bahKN-cIDtUBFbPyKsPblxJa6y_EAZTfKOfNJFBNEEPm-BI2wBbmP-uUYS3FjhT2ii_4Z6dxTLCgiuJ6cXHI_ASY5oUui0tfWrG4_j-H9fnaHvXYgJNNaZtjczaWCZ_l9QdaeZOZalQtwGa2aMRONbMdpzQtdXIc4gq6rmvE7DcfG2nI_"
};
